# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, default='', max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('classificacao', models.IntegerField()),
                ('miniatura', models.TextField()),
                ('pdf_path', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Disciplina'),
        ),
    ]
